#!/bin/bash

rm -r constant/polyMesh/cellLevel constant/polyMesh/sets constant/polyMesh/cellZones  constant/polyMesh/level0Edge  constant/polyMesh/pointLevel  constant/polyMesh/refinementHistory constant/polyMesh/boundary constant/polyMesh/faces constant/polyMesh/neighbour constant/polyMesh/points constant/polyMesh/setscellLevel constant/polyMesh/faceZones constant/polyMesh/owner constant/polyMesh/pointZones constant/polyMesh/surfaceIndex 0/cellLevel 0/nSurfaceLayers 0/pointLevel 0/thickness 0/thicknessFraction 0/*~
